"""
generate_sql.py  —  Step 3
----------------------------
Read flattened_formulas.json and the original workbook, then emit a
complete SQL query that is equivalent to the Excel summary sheet.

Output: output/output.sql
"""

import sys
import json
from pathlib import Path

import yaml
import networkx as nx

from lib.workbook import Workbook
from lib.dependency_graph import CellNode
from lib.formula_parser import parse_formula
from lib.flattener import flatten_all, detect_column_patterns, _col_letter, ColumnPattern
from lib.sql_emitter import SQLEmitter


def load_config() -> dict:
    with open(Path(__file__).parent / "config.yaml") as f:
        return yaml.safe_load(f)


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_sql.py <workbook.xlsx>")
        sys.exit(1)

    wb_path = Path(sys.argv[1])
    cfg = load_config()
    output_dir = Path(cfg["output_dir"])

    flat_path = output_dir / "flattened_formulas.json"
    graph_path = output_dir / "dependency_graph.json"

    for p in (flat_path, graph_path):
        if not p.exists():
            print(f"Missing: {p}. Run earlier pipeline steps first.")
            sys.exit(1)

    print(f"\nLoading flattened formulas: {flat_path}")
    with open(flat_path) as f:
        flat_data = json.load(f)
    with open(graph_path) as f:
        graph_data = json.load(f)

    output_sheet = flat_data["output_sheet"]
    max_depth = flat_data.get("max_substitution_depth", 20)

    # Reconstruct graph
    G = nx.DiGraph()
    for key, cell in graph_data["cells"].items():
        addr = (cell["sheet"], cell["row"], cell["col"])
        formula = cell["formula"]
        ast = parse_formula(formula) if formula else None
        node = CellNode(
            sheet=cell["sheet"], row=cell["row"], col=cell["col"],
            formula=formula, ast=ast, value=cell["value"],
            is_data=cell["is_data"],
        )
        G.add_node(addr, data=node)
    for src_key, dst_key in graph_data["edges"]:
        def _k(k):
            p = k.split("|")
            return (p[0], int(p[1]), int(p[2]))
        G.add_edge(_k(src_key), _k(dst_key))

    # Re-flatten (for AST objects — JSON doesn't store them)
    flattened = flatten_all(G, output_sheet, max_depth=max_depth)
    patterns = detect_column_patterns(flattened, output_sheet)

    # Load workbook header row for column labels
    print(f"Loading workbook for header labels...")
    wb = Workbook(wb_path)
    header_row = wb.header_row(output_sheet, header_row_num=1)
    print(f"  Headers on '{output_sheet}': {list(header_row.keys())[:10]}{'...' if len(header_row) > 10 else ''}")

    emitter = SQLEmitter(
        dialect=cfg.get("sql_dialect", "oracle"),
        schema=cfg.get("sql_schema", ""),
        overrides=cfg.get("function_overrides", {}),
    )

    print("\nGenerating SQL...")
    sql = emitter.emit_query(G, output_sheet, flattened, patterns, header_row)

    # Write output
    sql_path = output_dir / "output.sql"
    with open(sql_path, "w") as f:
        f.write(f"-- Generated by excel_tracer\n")
        f.write(f"-- Workbook : {wb_path}\n")
        f.write(f"-- Sheet    : {output_sheet}\n")
        f.write(f"-- Dialect  : {cfg.get('sql_dialect', 'oracle')}\n")
        f.write(f"-- Columns  : {len(flattened)} formula cells, {len(patterns)} vectorised\n")
        f.write("\n")
        f.write(sql)

    print(f"\n  Written: {sql_path}")
    print("\n" + "="*60)
    print(sql[:2000])
    if len(sql) > 2000:
        print(f"  ... ({len(sql) - 2000} more characters in file)")
    print("="*60)


if __name__ == "__main__":
    main()
